# Generated by Django 5.2.5 on 2025-10-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='libros/'),
        ),
        migrations.AddField(
            model_name='libro',
            name='sinopsis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
