# Generated by Django 5.2.5 on 2025-10-30 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_libro_imagen_libro_sinopsis'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Libro',
            new_name='Pelicula',
        ),
    ]
