# Generated by Django 5.2.5 on 2025-10-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_rename_libro_pelicula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='duracion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='fecha_lanzamiento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='precuela',
            field=models.TextField(blank=True, null=True),
        ),
    ]
