# Generated by Django 5.2.5 on 2025-10-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_remove_pelicula_descripcion_pelicula_duracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='secuela',
            field=models.TextField(blank=True, null=True),
        ),
    ]
