# Generated by Django 5.2.5 on 2025-10-30 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_pelicula_secuela'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='puntuacion',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
