# Generated by Django 5.2.5 on 2025-11-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_pelicula_puntuacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='peliculas/'),
        ),
    ]
